name: FAKE Build

on:
  push:   
  pull_request:
  workflow_dispatch:

jobs:
  win-build:
    name: Windows Build
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: System Info
        run: systeminfo 
        
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.401
         
      - name: Install OpenCL
        run: |
          set NUGETDIR=C:\NUGET
          nuget install opencl-nug -Version 0.777.77 -OutputDirectory %NUGETDIR%
          dir %NUGETDIR%\opencl-nug.0.777.77\build\native\
          set OCL_ROOT=%NUGETDIR%\opencl-nug.0.777.77\build\native
          # Install OpenCL Runtime
          choco install opencl-intel-cpu-runtime
                          
      - name: Build
        run: ./build.cmd
        env:
          CI: true
